GET http://localhost:5000/books

###
GET http://localhost:5000/books/62ff2c1806516204ef4f4aed

###
POST http://localhost:5000/books
Content-Type: application/json

{
    "book_title": "HTML CSS JS",
    "publisher": "Informatika",
    "genre": "Education"
}

###
PATCH http://localhost:5000/books/62ff2c1806516204ef4f4aed
Content-Type: application/json

{
    "book_title": "JavaScript",
    "publisher": "Informatika",
    "genre": "Programming Education"
}

###
DELETE http://localhost:5000/books/62ff2c7406516204ef4f4af0